### ISSUE TITLE
How to query from Google Sheet

### ISSUE THREAD

**Issue by havesomeleeway** [brandonmp/gatsby-source-google-sheets#13]
## Issue

I've set up my repository up to step 2, with the necessary information within `gatsby-config.js`  I have also managed to `gastby-develop` successfully. The question now is, how do I query data from my google sheet? 

Any form of help is appreciated, even if it's just pointing me in the right direction so that I can figure things out.

**Comment by camel113** [comment]
did you figure out how to use the plugin with GraphQL? I am unable to query the columns or cells of my sheets

**Comment by havesomeleeway** [comment]
Still havent managed to figure it out at all 🤷‍♂️, might just revert to using it with node.js instead

**Comment by drewatk** [comment]
Closing in favor of #22
