### ISSUE TITLE
Tutorial link in Step 1 is 404

### ISSUE THREAD

**Issue by joshbuchea** [brandonmp/gatsby-source-google-sheets#15]
The tutorial link in Step 1 is broken and results in a `404`:

> Follow this tutorial: https://www.twilio.com/blog/2017/03/google-spreadsheets-and-javascriptnode-js.html

**Comment by joshbuchea** [comment]
Potential alternative link: https://developers.google.com/sheets/api/quickstart/nodejs

**Comment by camel113** [comment]
This is also a good alternative link https://github.com/theoephraim/node-google-spreadsheet

**Comment by camel113** [comment]
@joshbuchea did you figure out how to use the plugin with GraphQL? I am unable to query the columns or cells of my sheets

**Comment by j-nolan** [comment]
@camel113 do you get any error or warnings? How far did you get?

Maybe your problem is related to #17. No nodes are returned if the sheet has only one row.

**Comment by camel113** [comment]
Yes it was the problem

**Comment by brandonmp** [comment]
closed by #16 , thx @j-nolan
