### ISSUE TITLE
Import stops after a single blank/empty row even if additional rows exist.

### ISSUE THREAD

**Issue by cgarvie** [brandonmp/gatsby-source-google-sheets#20]
Pretty self-explanatory. Just making a note for anyone else debugging. It thinks it's at the end of the sheet because of a single empty row.

**Comment by sahlhoff** [comment]
@cgarvie appears to be a `google-spreadsheet` issue: https://github.com/theoephraim/node-google-spreadsheet#row-based-api-limitations
