### ISSUE TITLE
How do I query from the plugin?

### ISSUE THREAD

**Issue by Tresky** [brandonmp/gatsby-source-google-sheets#21]
I am fairly new to Gatsby and GraphQL as a whole. I got all of the setup work done for this plugin to get permissions working. I'm unsure how to actually write the GraphQL query though. Anyone have any insight?

**Comment by drewatk** [comment]
Until we can get some docs up the best way is to use GraphiQL to make test queries, [which is built in to gatsby in development mode](https://www.gatsbyjs.org/tutorial/part-five/#introducing-graphiql).

Here's a sample query of getting all rows in a spreadsheet. The `title` and `description` are column headers in my spreadsheet.
```graphql
{
  allGoogleSheetSheet1Row {
    edges {
      node {
        title
        description
      }
    }
  }
}
```
