### ISSUE TITLE
Changes to the g-sheet data is not reflected in graphiql query result

### ISSUE THREAD

**Issue by ashokballolli** [brandonmp/gatsby-source-google-sheets#23]
Hi,
Thanks for this plugin. 
Curious to know how i can make it realtime synching of data from my g-sheet. Right now if i update the data to the g-sheet then its not reflecting in my graphiql query result unless i restart the application. Is there anything i am missing to configure. Thanks in advance

**Comment by drewatk** [comment]
This plug-in currently fetches all data at build time from Google sheets, so it's not possible as of now to change it to automatically fetch without rebuilding
