### ISSUE TITLE
Error with worksheets

### ISSUE THREAD

**Issue by Jossdz** [brandonmp/gatsby-source-google-sheets#31]
Hello ✌️

I'm getting an error and I already try with lots of things, can anyone help me ? 

![](https://i.postimg.cc/R0717j6m/Captura-de-Pantalla-2019-10-14-a-la-s-10-07-38.png)

**Comment by t0m0120** [comment]
@Jossdz 
How did you solve it?

**Comment by rjgux** [comment]
I'm also seeing this error. @Jossdz @t0m0120 Did you manage to work it out?

**Comment by Shree33** [comment]
BrandonMP updated the readme to include "If you get the error "Cannot read property 'worksheets' of undefined", make sure you have shared your spreadsheet with your service account user."
